
const FONT_FAMILY_NAMES = [
     'Limelight',
     'Lexend',
     'Abril Fatface',
     'Comfortaa',
     'Varela Round',
     'Teko',
     'Bebas Neue',
     'Lobster',
     'Josefin Sans',
     'Quicksand',
     'Dela Gothic One',
     'Nunito',
     'Raleway',
     'Poppins',
     'Montserrat',
     'Antonio',
     'Zen Dots',
     'Dancing Script',
     'Pacifico',
     'Prompt',
     'Questrial',
     'Fredoka One',
     'Righteous',
     'Cinzel',
     'Orbitron',
     'Playfair Display SC',
     'DM Serif Display',
     'Monoton',
     'Pirata One',
     'Julius Sans One',
     'Alata',
     'Varela',
     'Pinyon Script',
     'Reem Kufi',
     'Alegreya Sans SC',
     'Michroma',
     'Sen',
     'Cinzel Decorative',
     'Charm',
     'Marcellus SC',
     'Allerta Stencil',
     'Rozha One',
     'Rye',
     'Copse',
     'Merienda One',
     'Calligraffitti',
     'UnifrakturMaguntia',
     'Bowlby One',
     'Rammetto One',
     'Cherry Cream Soda',
     'Coiny',
     'UnifrakturCook',
     'Bellota',
     'Chango',
     'Lexend Exa',
     'Metal Mania',
     'Lexend Mega',
     'Lexend Giga',
     'Stalinist One',
     'Lexend Peta',
     'Nova Cut'
];
export default FONT_FAMILY_NAMES;
